#!/usr/bin/env bash
# Epure setup — ports, profiles, production secrets. Writes `.env` only when needed.
set -euo pipefail

ROOT="$(cd "$(dirname "$0")/.." && pwd)"
cd "$ROOT"

DEFAULT_EPURE_PORT=8080
DEFAULT_PG_PORT=5433

usage() {
  cat <<'EOF'
Epure setup helper (optional — default is plain `docker compose up`).

Usage: ./configure [options]

  --quick            Write .env only if 8080/5433 are busy (recommended)
  --dev              Vite CORS for web/ → .env
  --prod             Production .env (HTTPS URL + database secrets)
  --prod-rotate-secrets
                     New random DB secrets in .env and apply them to a running Postgres
  --sync-db-passwords
                     Apply POSTGRES_* secrets from .env to Postgres (existing volume)
  --port N           Set Epure host port → .env
  --postgres-port N  Set Postgres host port → .env
  --up               After configure, `docker compose up -d` + wait for /health
  --interactive      Menu wizard (quick / dev / custom / prod)
  --show             Print effective settings
  --reset            Remove .env
  -h, --help         This help

Most users:  docker compose up
Port clash:  cp .env.example .env  OR  ./configure --quick
Production:  ./configure --prod   # before first up, or after down -v
EOF
}

compose_project_name() {
  local name="${COMPOSE_PROJECT_NAME:-}"
  if [[ -z "$name" && -f .env ]]; then
    name="$(grep -E '^COMPOSE_PROJECT_NAME=' .env 2>/dev/null | tail -1 | cut -d= -f2- || true)"
  fi
  if [[ -z "$name" ]]; then
    name="$(basename "$ROOT")"
  fi
  printf '%s' "$name" | tr '[:upper:]' '[:lower:]'
}

postgres_data_volume_exists() {
  local project vol
  project="$(compose_project_name)"
  vol="${project}_postgres_data"
  docker volume inspect "$vol" >/dev/null 2>&1
}

env_has_prod_secrets() {
  local pg ingest app
  pg="$(read_env_value POSTGRES_PASSWORD "")"
  ingest="$(read_env_value EPURE_INGEST_PASSWORD "")"
  app="$(read_env_value EPURE_APP_PASSWORD "")"
  [[ -n "$pg" && -n "$ingest" && -n "$app" ]] || return 1
  [[ "$pg" != "CHANGE_ME" && "$ingest" != "CHANGE_ME" && "$app" != "CHANGE_ME" ]] || return 1
}

sync_db_passwords() {
  "${ROOT}/scripts/sync-db-passwords.sh"
}

print_prod_start_hint() {
  cat <<'EOF'
Start Caddy on ports 80 and 443 (certificate for your EPURE_SITE_ADDRESS):
  docker compose -f docker-compose.yml -f deploy/docker-compose.prod.yml --profile tls up -d

Drop --profile tls only if nginx, Caddy, or Traefik already serves your public URL.

Run ./configure --prod before the first `up`, or only after `docker compose … down -v`.
If you already have Postgres data, secrets in .env are reused or synced — never silently replaced.
EOF
}

port_in_use() {
  local port="$1"
  if command -v lsof >/dev/null 2>&1; then
    lsof -nP -iTCP:"$port" -sTCP:LISTEN -t >/dev/null 2>&1
    return
  fi
  (echo >/dev/tcp/127.0.0.1/"$port") >/dev/null 2>&1
}

find_free_port() {
  local port="$1"
  local limit="${2:-50}"
  local tries=0
  while port_in_use "$port"; do
    port=$((port + 1))
    tries=$((tries + 1))
    if [[ "$tries" -ge "$limit" ]]; then
      echo "No free port found near $1" >&2
      exit 1
    fi
  done
  echo "$port"
}

read_env_value() {
  local key="$1" default="${2:-}"
  if [[ -f .env ]]; then
    local line
    line="$(grep -E "^${key}=" .env 2>/dev/null | tail -1 || true)"
    if [[ -n "$line" ]]; then
      echo "${line#*=}"
      return
    fi
  fi
  echo "$default"
}

write_local_env() {
  local epure_port="$1" pg_port="$2" dev_seed="${3:-}" cors="${4:-}"
  {
    echo "# Generated by ./configure on $(date -u +%Y-%m-%dT%H:%MZ)"
    echo "EPURE_PORT=${epure_port}"
    echo "POSTGRES_HOST_PORT=${pg_port}"
    [[ -n "$dev_seed" ]] && echo "EPURE_DEV_SEED=1"
    [[ -n "$cors" ]] && echo "EPURE_CORS_ORIGINS=${cors}"
  } > .env
}

write_prod_env() {
  local epure_port="$1" public_url="$2" cors="$3" pg_pw="$4" ingest_pw="$5" app_pw="$6" site="$7"
  {
    echo "# Generated by ./configure --prod on $(date -u +%Y-%m-%dT%H:%MZ)"
    echo "EPURE_PORT=${epure_port}"
    echo "EPURE_PUBLIC_URL=${public_url}"
    echo "EPURE_SITE_ADDRESS=${site}"
    echo "EPURE_CORS_ORIGINS=${cors}"
    echo "POSTGRES_PASSWORD=${pg_pw}"
    echo "EPURE_INGEST_PASSWORD=${ingest_pw}"
    echo "EPURE_APP_PASSWORD=${app_pw}"
  } > .env
}

pick_ports() {
  local epure_port pg_port
  epure_port="$DEFAULT_EPURE_PORT"
  pg_port="$DEFAULT_PG_PORT"
  if port_in_use "$epure_port"; then
    epure_port="$(find_free_port "$epure_port")"
    echo "Port ${DEFAULT_EPURE_PORT} is in use → using ${epure_port}" >&2
  fi
  if port_in_use "$pg_port"; then
    pg_port="$(find_free_port "$pg_port")"
    echo "Port ${DEFAULT_PG_PORT} is in use → using ${pg_port}" >&2
  fi
  EPURE_PORT="$epure_port"
  POSTGRES_PORT="$pg_port"
}

show_config() {
  local epure_port pg_port public_url
  epure_port="$(read_env_value EPURE_PORT "$DEFAULT_EPURE_PORT")"
  pg_port="$(read_env_value POSTGRES_HOST_PORT "$DEFAULT_PG_PORT")"
  public_url="$(read_env_value EPURE_PUBLIC_URL "")"
  if [[ -z "$public_url" ]]; then
    public_url="http://localhost:${epure_port} (auto)"
  fi
  echo "Epure configuration"
  echo "  .env file:     $([[ -f .env ]] && echo yes || echo no)"
  echo "  EPURE_PORT:    ${epure_port}"
  echo "  POSTGRES_PORT: ${pg_port}"
  echo "  Public URL:    ${public_url}"
  echo "  Open:          http://localhost:${epure_port}"
  if [[ -f .env ]] && grep -q '^EPURE_DEV_SEED=1' .env; then
    echo "  Profile:       fixed-UUID scaffold on startup (EPURE_DEV_SEED)"
  fi
}

print_next_steps() {
  local epure_port="$1"
  cat <<EOF

Next:
  docker compose up          # foreground
  docker compose up -d       # background

Open:  http://localhost:${epure_port}
Health: curl -sS http://localhost:${epure_port}/health

Production: ./configure --prod
EOF
}

wait_for_health() {
  local port="$1" i
  echo "Waiting for http://localhost:${port}/health ..."
  for i in $(seq 1 90); do
    if curl -fsS "http://localhost:${port}/health" >/dev/null 2>&1; then
      echo "Ready → http://localhost:${port}"
      return 0
    fi
    sleep 2
  done
  echo "Timed out waiting for health. Check: docker compose logs -f epure" >&2
  return 1
}

run_up() {
  local port
  port="$(read_env_value EPURE_PORT "$DEFAULT_EPURE_PORT")"
  docker compose up -d
  wait_for_health "$port"
}

gen_secret() {
  if command -v openssl >/dev/null 2>&1; then
    openssl rand -base64 32 | tr -d '/+=' | head -c 32
  else
    # shellcheck disable=SC2155
    local r
    r="$(date +%s%N 2>/dev/null || date +%s)"
    echo "epure-${r}-$(printf '%04x' $((RANDOM * RANDOM)))"
  fi
}

prompt() {
  local label="$1" default="$2" value
  if [[ -n "$default" ]]; then
    read -r -p "${label} [${default}]: " value
    echo "${value:-$default}"
  else
    read -r -p "${label}: " value
    echo "$value"
  fi
}

mode_quick() {
  pick_ports
  if [[ "$EPURE_PORT" == "$DEFAULT_EPURE_PORT" && "$POSTGRES_PORT" == "$DEFAULT_PG_PORT" ]]; then
    echo "Ports ${DEFAULT_EPURE_PORT} and ${DEFAULT_PG_PORT} are free."
    echo "No .env needed — run: docker compose up"
    echo "Open: http://localhost:${DEFAULT_EPURE_PORT}"
    return 0
  fi
  write_local_env "$EPURE_PORT" "$POSTGRES_PORT"
  echo "Wrote .env (busy defaults avoided)."
  print_next_steps "$EPURE_PORT"
}

mode_dev() {
  pick_ports
  write_local_env "$EPURE_PORT" "$POSTGRES_PORT" "" "http://localhost:5173"
  echo "Wrote .env — developer profile (Vite CORS)."
  echo "Preview data: register at /login. Heavy UX: ./scripts/seed.sh --email … --password …"
  print_next_steps "$EPURE_PORT"
}

mode_custom() {
  local epure_port pg_port cors
  pick_ports
  epure_port="$(prompt "Epure host port" "$EPURE_PORT")"
  pg_port="$(prompt "Postgres host port" "$POSTGRES_PORT")"
  read -r -p "Extra CORS origin (blank = default *): " cors
  write_local_env "$epure_port" "$pg_port" "" "$cors"
  echo "Wrote .env"
  print_next_steps "$epure_port"
}

prod_site_address() {
  local public_url="$1" host
  if [[ ! "$public_url" =~ ^https:// ]]; then
    echo "Public URL must start with https://" >&2
    return 1
  fi
  host="${public_url#https://}"
  host="${host%%/*}"
  host="${host%%:*}"
  host="${host#[}"
  host="${host%]}"
  if [[ -z "$host" || "$host" == "localhost" || "$host" =~ ^[0-9.]+$ || "$host" == *:* ]]; then
    echo "Use a DNS name such as https://errors.example.com." >&2
    echo "A raw IP cannot get a browser-trusted certificate. Sign-in on http://IP:${DEFAULT_EPURE_PORT} will not stick." >&2
    return 1
  fi
  printf '%s\n' "$host"
}

mode_prod() {
  local rotate="${1:-0}"
  local epure_port public_url cors pg_pw ingest_pw app_pw site
  local vol_exists=false reuse_secrets=false apply_to_db=false

  if postgres_data_volume_exists; then
    vol_exists=true
  fi

  epure_port="$(prompt "Epure host port (behind reverse proxy)" "$(read_env_value EPURE_PORT "$DEFAULT_EPURE_PORT")")"
  public_url="$(prompt "Public HTTPS URL" "$(read_env_value EPURE_PUBLIC_URL "https://errors.example.com")")"
  site="$(prod_site_address "$public_url")" || exit 1
  cors="$(prompt "CORS origins (comma-separated)" "$(read_env_value EPURE_CORS_ORIGINS "$public_url")")"

  if [[ "$rotate" == 1 ]]; then
    if [[ "$vol_exists" == true ]]; then
      read -r -p "Generate new database secrets and apply them to the existing Postgres volume? [y/N]: " confirm
      if [[ ! "$confirm" =~ ^[yY] ]]; then
        echo "Aborted."
        exit 0
      fi
    fi
    pg_pw="$(gen_secret)"
    ingest_pw="$(gen_secret)"
    app_pw="$(gen_secret)"
    apply_to_db="$vol_exists"
  elif [[ "$vol_exists" == true ]] && env_has_prod_secrets; then
    pg_pw="$(read_env_value POSTGRES_PASSWORD "")"
    ingest_pw="$(read_env_value EPURE_INGEST_PASSWORD "")"
    app_pw="$(read_env_value EPURE_APP_PASSWORD "")"
    reuse_secrets=true
    echo "Postgres data volume found — keeping database secrets from .env (URLs and CORS updated)." >&2
  else
    pg_pw="$(gen_secret)"
    ingest_pw="$(gen_secret)"
    app_pw="$(gen_secret)"
    if [[ "$vol_exists" == true ]]; then
      apply_to_db=true
      echo "Postgres data volume found — new secrets will be written to .env and applied inside Postgres." >&2
    fi
  fi

  write_prod_env "$epure_port" "$public_url" "$cors" "$pg_pw" "$ingest_pw" "$app_pw" "$site"

  if [[ "$apply_to_db" == true ]]; then
    sync_db_passwords
  fi

  cat <<EOF

Wrote production .env — back this file up.

Sign in at ${public_url}/login
Do not open http://THIS_SERVER:${epure_port}
/health can succeed there. Login cannot. The Secure cookie is dropped and the form returns with no error.
EOF
  if [[ "$reuse_secrets" == true ]]; then
    echo "Database passwords unchanged (matched existing volume)."
  elif [[ "$apply_to_db" == true ]]; then
    echo "Database passwords updated to match .env."
  else
    echo "Database passwords generated for a new Postgres volume."
  fi
  echo ""
  print_prod_start_hint
}

mode_prod_rotate() {
  mode_prod 1
}

mode_interactive() {
  cat <<'EOF'

Epure setup
───────────
  1  Quick start   — defaults; .env only if ports are busy (recommended)
  2  Developer     — demo data + Vite CORS (localhost:5173)
  3  Custom        — pick ports and options
  4  Production    — VPS / HTTPS (.env + prod overlay)
  q  Quit          — use plain `docker compose up` with no .env

EOF
  local choice
  read -r -p "Choice [1]: " choice
  choice="${choice:-1}"
  case "$choice" in
    1) mode_quick ;;
    2) mode_dev ;;
    3) mode_custom ;;
    4) mode_prod ;;
    q|Q) echo "Skipped. Run: docker compose up" ;;
    *) echo "Unknown choice." >&2; exit 1 ;;
  esac
}

DO_UP=0
EPURE_PORT_ARG=""
PG_PORT_ARG=""

while [[ $# -gt 0 ]]; do
  case "$1" in
    -h|--help) usage; exit 0 ;;
    --interactive|-i) MODE=interactive; shift ;;
    --quick) MODE=quick; shift ;;
    --dev) MODE=dev; shift ;;
    --prod) MODE=prod; shift ;;
    --prod-rotate-secrets) MODE=prod_rotate; shift ;;
    --sync-db-passwords)
      sync_db_passwords
      exit 0
      ;;
    --up) DO_UP=1; shift ;;
    --show) show_config; exit 0 ;;
    --reset)
      rm -f .env
      echo "Removed .env (Compose defaults apply)."
      exit 0
      ;;
    --port) EPURE_PORT_ARG="$2"; shift 2 ;;
    --postgres-port) PG_PORT_ARG="$2"; shift 2 ;;
    *)
      echo "Unknown option: $1" >&2
      usage >&2
      exit 1
      ;;
  esac
done

if [[ -n "$EPURE_PORT_ARG" || -n "$PG_PORT_ARG" ]]; then
  epure_port="${EPURE_PORT_ARG:-$DEFAULT_EPURE_PORT}"
  pg_port="${PG_PORT_ARG:-$DEFAULT_PG_PORT}"
  write_local_env "$epure_port" "$pg_port"
  echo "Wrote .env"
  print_next_steps "$epure_port"
elif [[ -n "${MODE:-}" ]]; then
  case "$MODE" in
    quick) mode_quick ;;
    dev) mode_dev ;;
    prod) mode_prod 0 ;;
    prod_rotate) mode_prod_rotate ;;
    interactive) mode_interactive ;;
  esac
else
  echo "Default install needs no setup: docker compose up"
  echo ""
  usage
  exit 0
fi

if [[ "$DO_UP" == 1 ]]; then
  run_up
fi
